### ISSUE TITLE
引导出错解决方法

### ISSUE THREAD

**Issue by 56934994** [ngfuong/xps-13-9370-hackintosh#1]
如果引导报OCB：StartImage failed - Aborted，
把Booter下的Quirks下的DevirtualiseMmio打勾可以解决

**Comment by ngfuong** [comment]
Could you translate your issue to English?

**Comment by 56934994** [comment]
![Uploading IMG_20211009_210432.jpg…]()

**Comment by 56934994** [comment]
My computer is XPS 9370, the CPU is i78550u, and the graphics card is hd620. After using your EIF, the system cannot start, and the prompt OCB: startimage failed - aborted. After enabling devitalisemmio, you can enter the system, but the model is displayed as MAC, the CPU is unknown, and there is a problem with the keyboard. What can be done to solve it?

**Comment by ngfuong** [comment]
It's supposed to display as a Mac.
My graphics card is UHD620. You can read my laptop's configurations in the README.md and see if there's any other difference. Could you provide your hardware spec?
For the keyboard you could try multiple other Voodoo kexts other than VoodooI2C and PS2.
You can try using the original EFI from @QuantumShqipe, I also provide the link to their repo in README.md.

**Comment by 56934994** [comment]
---原始邮件---
发件人: "Phuong N. ***@***.***&gt;
发送时间: 2021年10月10日(周日) 凌晨1:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ngfuong/xps-13-9370-hackintosh] 引导出错解决方法 (#1)




 
It's supposed to display as a Mac.
 You can read my laptop's configurations in the README.md and see if there's any difference. Could you provide your hardware spec?
 For the keyboard you could try multiple other Voodoo kexts other than VoodooI2C and PS2.
 You can try using the original EFI from @QuantumShqipe, I also provide the link to their repo in README.md.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
